### ISSUE TITLE
Adaption to OMV 5

### ISSUE THREAD

**Issue by Haxe18** [OpenMediaVault-Plugin-Developers/openmediavault-dnsmasq#5]
Hey maintainer,

is an update to OMV 5 planned for this plugin ?
Would like to use it, but it's not working on OMV5, error is _omv-mkconf: not found_ but i think there is a bit more to adapt 😬

Thanks in advance

**Comment by ryecoaaron** [comment]
No, I was not going to port to OMV 5.x.  You can see which plugins have been ported here - https://forum.openmediavault.org/index.php?thread/24545-why-should-you-use-or-not-use-dockers/&postID=186122#post186122

I suggest using pi-hole in a docker.

**Comment by Haxe18** [comment]
Okay thanks for the answer.
I am searching for an Plugin to do DHCP on my OMV because i've attached an Data only lan in which i want to lease ips.
I think I will take a look what docker hub offers for this case, thanks for the hint.

**Comment by ryecoaaron** [comment]
I use pi-hole for dhcp myself.
